name: charts_common
version: 0.13.0
description: A common library for charting packages.
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  intl: ^0.17.0
  logging: ^1.0.2
  meta: ^1.7.0
  vector_math: ^2.1.2

dev_dependencies:
  mockito: ^5.2.0
  test: ^1.21.1
